### ISSUE TITLE
Continue Button on Install Wizard Does Nothing

### ISSUE THREAD

**Issue by hismightiness** [DNNCommunity/Dnn.CommunityForums#34]
## Describe the bug
There is a Continue button that allows you to do a quick setup when adding the module to a page.  

## Software Versions
- DNN: 09.04.00+
- Module: 06.04.00

## To Reproduce
1. Install the module
2. Create a page
3. Add the module to a page
4. Click the `Continue` button

## Expected behavior
The forum gets setup with minimum settings.  Instead, the page reloads with nothing having happened.  

## Screenshots
![image](https://user-images.githubusercontent.com/938023/99838243-a8256100-2b1d-11eb-94f5-92ba29fdd1fc.png)

## Error log
```  
Message:Could not find file 'C:\Work\Platform\platform962\Website\DesktopModules\ActiveForums\config\defaultsetup.config'.

StackTrace:

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.OpenUrlDelegate(Object xmlResolver)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.CompressedStack.Run(CompressedStack compressedStack, ContextCallback callback, Object state)
   at System.Xml.XmlTextReaderImpl.OpenUrl()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at DotNetNuke.Modules.ActiveForums.ForumsConfig.LoadDefaultForums(Int32 PortalId, Int32 ModuleId)
   at DotNetNuke.Modules.ActiveForums.ForumsConfig.ForumsInit(Int32 PortalId, Int32 ModuleId)
```

**Comment by hismightiness** [comment]
This is a bug in the build process that packages the module.
