### ISSUE TITLE
Active Forums Crashes When Clicking to View Image

### ISSUE THREAD

**Issue by tonyatl2** [DNNCommunity/Dnn.CommunityForums#59]
## Describe the bug
When i click on an image i have uploaded to a forum topic, active forums crashes with a message stating that a critical error has occurred.

## Software Versions
- DNN: 9.8.1
- Module: 6.5

## To Reproduce
1. Navigate to active forums forum
2. Click on New New Topic
3. Upload an Image (attachment)
4. Click the image icon/link in the topic
5. Second tab of browser opens with error message noted above

## Expected behavior
I expect the image to render without any error. My image was not rendered because of the sql error reported in the log

## Error log
**Note: Debug DLL's**
AbsoluteURL:/DesktopModules/ActiveForums/viewer.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:810ad2c6-d9bf-41c2-8afc-5900d4c2d80a

AssemblyVersion:9.8.1

PortalId:0

UserId:1

TabId:22

RawUrl:/DesktopModules/ActiveForums/viewer.aspx?portalid=0&moduleid=409&attachmentid=1

Referrer:https://www.etiquemarket.com/forums/aft/1

UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36

ExceptionHash:/VFfOZMMg9MveQQqJsZTO0DUn/8=

Message:Invalid object name 'dbo.vw_activeforums_TopicView as tv on tv.ContentId = A.ContentId INNER JOIN dbo.[activeforums_ForumTopics'.

StackTrace:

InnerMessage:Invalid object name 'dbo.vw_activeforums_TopicView as tv on tv.ContentId = A.ContentId INNER JOIN dbo.[activeforums_ForumTopics'.

InnerStackTrace:

at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
at System.Data.SqlClient.SqlDataReader.get_MetaData()
at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteReader(SqlConnection connection, SqlTransaction transaction, CommandType commandType, String commandText, SqlParameter[] commandParameters, SqlConnectionOwnership connectionOwnership)
at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteReader(String connectionString, CommandType commandType, String commandText, SqlParameter[] commandParameters)
at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteReader(String connectionString, String spName, Object[] parameterValues)
at DotNetNuke.Modules.ActiveForums.Data.AttachController.Get(Int32 attachmentId, Int32 fileId, Boolean withSecurity)
at DotNetNuke.Modules.ActiveForums.af_viewer.OnLoad(EventArgs e)
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:
 0

**Comment by hismightiness** [comment]
How are you getting to this point?  I'm unable to choose any file to upload as an attachment.  Was this upgraded from an older version of the module?

**Comment by tonyatl2** [comment]
just as i described. I had to accommodate my content security policy to enable some behaviors on the way to getting to the attachments button. but once i uploaded the image, a grey box was rendered which i clicked to view the image. then i got the error described. i have attached an image though i can't see it.

i installed 6.5 fresh.

**Comment by tonyatl2** [comment]
ps - i see this error in browser developer tools: Failed to load resource: the server responded with a status of 404 () /desktopmodules/activeforums/handlers/forumhelper.ashx?TabId=46&PortalId=0&moduleid=409&language=en-US

this message appears before clicking the image link.

**Comment by Timo-Breumelhof** [comment]
Thank you for logging this.

**Comment by hismightiness** [comment]
> ps - i see this error in browser developer tools: Failed to load resource: the server responded with a status of 404 () /desktopmodules/activeforums/handlers/forumhelper.ashx?TabId=46&PortalId=0&moduleid=409&language=en-US
> 
> this message appears before clicking the image link.
> 
> finally, i see this error - Uncaught TypeError: Cannot read property 'mozilla' of undefined
> at HTMLDocument. (1:566)
> at e (js:1)
> at t (js:1)
> 
> not sure from where it comes - dnn, active forums, the theme?

It appears to be in the module, not the theme.

**Comment by puresystems** [comment]
We are having a similar problem (with clean install of v6.6.0 on DNN9.9.1). We see the JS error as described, but also an error is logged in DNN.

The attached images are shows as links, an example link is:
/DesktopModules/ActiveForums/viewer.aspx?portalid=0&moduleid=649&attachmentid=1

When clicked, a new browser window opens with this URL:
/Default.aspx?tabid=33&error=An%20unexpected%20error%20has%20occurred&content=0

This is from the DNN log:
AbsoluteURL:/DesktopModules/ActiveForums/viewer.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:db6e30e6-0ff2-4c6e-baef-6488513e5412
AssemblyVersion:9.9.1
PortalId:0
UserId:10
TabId:33
RawUrl:/DesktopModules/ActiveForums/viewer.aspx?portalid=0&amp;moduleid=649&amp;attachmentid=1
Referrer:/members/forums/aft/4
UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36 Edg/94.0.992.31
ExceptionHash:/VFfOZMMg9MveQQqJsZTO0DUn/8=
Message:Invalid object name 'dbo.vw_activeforums_TopicView as tv on tv.ContentId = A.ContentId INNER JOIN dbo.[activeforums_ForumTopics'.
StackTrace:
InnerMessage:Invalid object name 'dbo.vw_activeforums_TopicView as tv on tv.ContentId = A.ContentId INNER JOIN dbo.[activeforums_ForumTopics'.
InnerStackTrace:
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteReader(SqlConnection connection, SqlTransaction transaction, CommandType commandType, String commandText, SqlParameter[] commandParameters, SqlConnectionOwnership connectionOwnership)
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteReader(String connectionString, CommandType commandType, String commandText, SqlParameter[] commandParameters)
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteReader(String connectionString, String spName, Object[] parameterValues)
   at DotNetNuke.Modules.ActiveForums.Data.AttachController.Get(Int32 attachmentId, Int32 fileId, Boolean withSecurity)
   at DotNetNuke.Modules.ActiveForums.af_viewer.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by puresystems** [comment]
I've had a look through the SQL stored proc and there's a typo as follows:

[dbo].[activeforums_Attachments_Get]

Line 16:
inner join dbo.[vw_activeforums_TopicView as tv on tv.ContentId = A.ContentId

Change to:
inner join dbo.[vw_activeforums_TopicView] as tv on tv.ContentId = A.ContentId

There was a missing closing square bracket around the view name. This now allows the download of attachments.

**Comment by hismightiness** [comment]
Outstanding find!  Here is the code we need to get in as a PR for the next release.

```sql  
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'{databaseOwner}[{objectQualifier}activeforums_Attachments_Get]') AND type in (N'P', N'PC'))
DROP PROCEDURE {databaseOwner}[{objectQualifier}activeforums_Attachments_Get];
GO

CREATE PROCEDURE {databaseOwner}[{objectQualifier}activeforums_Attachments_Get]
@AttachmentID int,
@FileID int,
@WithSecurity bit = 0
AS
BEGIN
	SET NOCOUNT ON
	If @WithSecurity = 0
		SELECT AttachID, ContentId, IsNull(UserID,-1) as UserID, [Filename], FileData, ContentType, FileSize, FileID, AllowDownload
		FROM {databaseOwner}[{objectQualifier}activeforums_Attachments]
		WHERE (@AttachmentId > 0 AND AttachID = @AttachmentID)
			OR (@FileID > 0 AND @FileID = FileID)
	ELSE
		SELECT A.AttachID, A.ContentId, ISNULL(A.UserID, - 1) AS UserID, A.Filename, A.FileData, A.ContentType, A.FileSize, A.FileID, A.AllowDownload, p.CanRead
		FROM {databaseOwner}[{objectQualifier}activeforums_Attachments] A
		inner join {databaseOwner}[{objectQualifier}vw_activeforums_TopicView] as tv on tv.ContentId = A.ContentId
		INNER JOIN {databaseOwner}[{objectQualifier}activeforums_ForumTopics] FT ON FT.TopicId = tv.TopicId 
		INNER JOIN {databaseOwner}[{objectQualifier}activeforums_Forums] AS F ON F.ForumId	 = FT.ForumId		
		INNER JOIN {databaseOwner}[{objectQualifier}activeforums_Permissions] AS p ON p.PermissionsId = F.PermissionsId 
		WHERE (@AttachmentID > 0 AND AttachID = @AttachmentID)
			OR (@FileID > 0 AND @FileID = FileID)
END
```

**Comment by johnhenley** [comment]
Hi, I encountered this issue as well, and want to assist by putting in the pull request and associated change. I also have other tweaks that I would like to push back into the community edition. While I can figure out how to modify and/or change existing code files in my forked version, and enter a pull request, there is one thing I don't quite understand and don't want to step on anything....

If one needs to introduce a new or updated SQL procedure, how do you name the xx.xx.xx.SqlDataProvider file if you don't have a new release -- do you just make up a new number? 
Thanks.

**Comment by skamphuis** [comment]
I've wondered about that too, but I guess it will need some work anyway when merging the PR, so maybe just give it a name and mention it in the comments for the pull request should do?

**Comment by WillStrohl** [comment]
I'd just suggest looking to see which are the next milestone and use that.  If the project owner(s) decide the version should be different, then we can do or request that as part of the PR dialog prior to accepting merging it.  

[https://github.com/DNNCommunity/Dnn.CommunityForums/milestones](https://github.com/DNNCommunity/Dnn.CommunityForums/milestones)

**Comment by johnhenley** [comment]
Thanks. Follow up question: what visual studio version and DNN do you recommend for test/dev builds?

John
________________________________

**Comment by WillStrohl** [comment]
I'm using VS 2019 for most things these days, including this module.

**Comment by WillStrohl** [comment]
You can look at either the project file or manifest file in most projects to see which version of DNN to build against.  

Manifest Example:  https://github.com/DNNCommunity/Dnn.CommunityForums/blob/dev/ActiveForums.dnn#L17
Project Example:  https://github.com/DNNCommunity/Dnn.CommunityForums/blob/dev/ActiveForums.csproj#L68-L70

The project file DNN version is the most important one to pay attention to.  :)

**Comment by Timo-Breumelhof** [comment]
@johnhenley Great to hear that you want to help improve the Module. :-)

**Comment by Timo-Breumelhof** [comment]
@johnhenley we want to release a new version soon, would you be able to supply us with a PR? :-)

**Comment by johnhenley** [comment]
Hopefully I got this in OK…

**Comment by Timo-Breumelhof** [comment]
Ok, cool, thanks :-)

**Comment by johnhenley** [comment]
Yes, I didn't know what version you were aiming for. Do you want me to update that?

**Comment by Timo-Breumelhof** [comment]
yes please :-)

**Comment by johnhenley** [comment]
done

**Comment by Timo-Breumelhof** [comment]
thanks :-)

**Comment by johnhenley** [comment]
How soon do you plan to do a release? I might take another crack at issue #13 since it seems it never really got fixed?

**Comment by Timo-Breumelhof** [comment]
It will take at least a few weeks there are a few I want fix myself too.

**Comment by Timo-Breumelhof** [comment]
> How soon do you plan to do a release? I might take another crack at issue #13 since it seems it never really got fixed?

If you could fix #13 that would be really great :-)

**Comment by johnhenley** [comment]
Hi Timo, 
I tried to figure out how to contact you directly rather than via a comment. I need some help :)

I put in an additional issue related to the friendly url rewriter, so I know have two issues related to that, and have fixes for both.

However, I'm running into a problem with creating the pull request, since 1) I still have the outstanding pull request #114 and github keeps trying to attach everything I've changed to that one. Do you have to accept the outstanding pull request before I can create a new one? Also, I updated the .csproj file on my local machine, and despite my best attempts, git also wants to include that change, despite me reverting and resetting to the point where it now looks like I have a dozen commits :)

I used Azure DevOps with TFVC so Git is a little foreign to me :)

Thanks, and let me know what I can do...

**Comment by Timo-Breumelhof** [comment]
@johnhenley So #114 now only has the fix for #59 in it?
I was already wondering why you had so many commits, n.p. GIT takes time to get used to.
(took me a long time TBH, although I do like it now)

The way I do this in GIT is to create a separate feature branch for each issue, typically as /feature/19
As long as you commit from one branch, every change in that branch will part of the outstanding PR.

You can contact me via timo at 40fingers dot net if you want

**Comment by johnhenley** [comment]
"As long as you commit from one branch, every change in that branch will part of the outstanding PR."

So if I have multiple bug and/or feature branches, do they all get rolled into a single pull request to the upstream repo? If so, is that desirable? I'm concerned that it gets confusing. Or is there a way to do one pull request per feature/bug branch?

**Comment by johnhenley** [comment]
> @johnhenley So #114 now only has the fix for #59 in it?

@Timo-Breumelhof #114 fixes #59 and #106. I also have code ready to fix #13 if you want that included in this PR or if that goes in separate PR (that's my concern/confusion about single vs multiple PRs).

**Comment by Timo-Breumelhof** [comment]
ok, so ideally #114 should only ave a fix for one issue.
But we'll deal with that, leave it this way.
for #13, please create a new branch based on Master and make your changes for #13 in there. This should then result in a separate PR with only the fix for #13 in it.

**Comment by johnhenley** [comment]
I’m tempted to ask you to reject #114 I make me start over :)

John
________________________________

**Comment by johnhenley** [comment]
Please reject it. I need the practice:)

John
________________________________

**Comment by Timo-Breumelhof** [comment]
ok :-)
