### ISSUE TITLE
Crash on reply on post with code

### ISSUE THREAD

**Issue by Tychodewaard** [DNNCommunity/Dnn.CommunityForums#76]
## Describe the bug
On https://dnncommunity.org/forums/aft/82 you'll find a post from Timo with some code.
If you click on reply, the site throws an error: The service is unavailable.

The DNN log says:
AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:de1cba88-2d66-4b79-96b8-d0a50c7cd0a1

AssemblyVersion:

PortalId:-1

UserId:-1

TabId:-1

RawUrl:

Referrer:

UserAgent:

ExceptionHash:zOEC8Bv8vqZZgnPrWE6893fWfoc=

Message:'"fortyfingers"' is not a valid value for attribute 'tagprefix'.

StackTrace:

InnerMessage:'"fortyfingers"' is not a valid value for attribute 'tagprefix'.

InnerStackTrace:

   at System.Web.UI.TemplateParser.ParseString(String text, VirtualPath virtualPath, Encoding fileEncoding)
   at System.Web.UI.TemplateParser.ParseInternal()
   at System.Web.UI.TemplateParser.Parse()
   at System.Web.UI.TemplateParser.ParseTemplateInternal(String content, VirtualPath virtualPath, Boolean ignoreFilter)
   at System.Web.UI.TemplateParser.ParseControl(String content, VirtualPath virtualPath, Boolean ignoreFilter)
   at DotNetNuke.Modules.ActiveForums.Controls.SubmitForm.LoadForm()
   at DotNetNuke.Modules.ActiveForums.Controls.SubmitForm.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.<LoadRecursiveAsync>d__246.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult()
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
Source:

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

Server Name: HYPV8648

## Software Versions
- DNN: 9

**Comment by Timo-Breumelhof** [comment]
Ok, I just tried this on my local version with this fix: https://github.com/DNNCommunity/Dnn.CommunityForums/pull/74 and with the <% code in the post, it works fine.

**Comment by Timo-Breumelhof** [comment]
FYI, the module used to have encoding issues, where <% posted as text would get converted to <% in source HTML, and at that moment DNN/.net security kicks in IMO. I removed that encode / decode issue and that should IMO fix this issue too.

**Comment by hismightiness** [comment]
@Timo-Breumelhof  So this is already fixed in the PR you mentioned?

**Comment by Timo-Breumelhof** [comment]
@hismightiness I think so, but if we test the new version on dnncommunity we will know for sure :-)
