### ISSUE TITLE
Missing Stored Procedure

### ISSUE THREAD

**Issue by liffeyd** [DNNCommunity/Dnn.CommunityForums#82]
## Please summarize your question in one sentence

Errors in DNN log:

The stored procedure 'dbo.activeforums_Search_ManageFullText' doesn't exist.

This appears to have happened after I turned on FUll Text Search.

The site is running Active Forums 6.5.1.

**Comment by liffeyd** [comment]
When I look at module settings  Active Forums Settings > Advanced Options > Enable-Full-Text-Search the option is off, even though I had turned it on. 

If I click Update, to "save" the option as off, I continue to get the Module Load Exception - SP missing error shown above.

I also get a Page Load Exception:

`AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:927b3973-8635-4a83-9bf1-ac3bba2861fd

AssemblyVersion:9.9.0

PortalId:0

UserId:1

TabId:69

RawUrl:/Forum/ctl/Module/ModuleId/434?ReturnURL=/Forum&amp;popUp=true

Referrer:https://www.XXXXXXXXXX/Forum/ctl/Module/ModuleId/434?ReturnURL=/Forum&amp;popUp=true

UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0

ExceptionHash:j91ENZzp9Do4afjNUkyNRvYTGRw=

Message:The Controls collection cannot be modified because the control contains code blocks (i.e. <% ... %>).

StackTrace:

InnerMessage:The Controls collection cannot be modified because the control contains code blocks (i.e. <% ... %>).

InnerStackTrace:

   at System.Web.UI.ControlCollection.Add(Control child)
   at DotNetNuke.Services.Exceptions.Exceptions.ProcessModuleLoadException(String FriendlyMessage, Control ctrl, Exception exc, Boolean DisplayErrorMessage)

Source:

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

Server Name: `

**Comment by hismightiness** [comment]
@liffeyd  Did this instance begin from an older version of Active Forums?

**Comment by liffeyd** [comment]
@hismightiness Yes it did.

**Comment by hismightiness** [comment]
Ah... Yes, then there was probably something missed in one of the releases.  Not by you, but in the release itself.  It will need some troubleshooting to figure out.

**Comment by Timo-Breumelhof** [comment]
FYI, I just reproduced this on my local development install while testing Full Text Search

**Comment by Timo-Breumelhof** [comment]
Ok this was all due to this issue, which will be in the next release: https://github.com/DNNCommunity/Dnn.CommunityForums/issues/111
